"""Added created_at updated_at base fields

Revision ID: 2c73d9c12c5a
Revises: f6d6e448ee7a
Create Date: 2024-09-15 11:22:27.127926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c73d9c12c5a'
down_revision: Union[str, None] = 'f6d6e448ee7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asteroid', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('asteroid', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asteroid', 'updated_at')
    op.drop_column('asteroid', 'created_at')
    # ### end Alembic commands ###