"""empty message

Revision ID: 3722f0113bc1
Revises: 2c73d9c12c5a
Create Date: 2024-09-29 08:33:13.143531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3722f0113bc1'
down_revision: Union[str, None] = '2c73d9c12c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'asteroid', ['designation'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asteroid', type_='unique')
    # ### end Alembic commands ###