"""empty message

Revision ID: f6d6e448ee7a
Revises: 
Create Date: 2024-09-15 09:21:46.492308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f6d6e448ee7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asteroid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discovery_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('h_mag', sa.Float(), nullable=True),
    sa.Column('moid_au', sa.Float(), nullable=True),
    sa.Column('q_au_1', sa.Float(), nullable=True),
    sa.Column('q_au_2', sa.Float(), nullable=True),
    sa.Column('period_yr', sa.Float(), nullable=True),
    sa.Column('i_deg', sa.Float(), nullable=True),
    sa.Column('pha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orbit_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asteroid')
    # ### end Alembic commands ###